
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.16.0

#include <stan/model/model_header.hpp>

namespace model_vb_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_vb");
    reader.add_event(18, 18, "end", "model_vb");
    return reader;
}

class model_vb : public prob_grad {
private:
    int N;
    vector_d length;
    vector_d age;
public:
    model_vb(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_vb(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_vb_namespace::model_vb";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        context__.validate_dims("data initialization", "N", "int", context__.to_vec());
        N = int(0);
        vals_i__ = context__.vals_i("N");
        pos__ = 0;
        N = vals_i__[pos__++];
        validate_non_negative_index("length", "N", N);
        context__.validate_dims("data initialization", "length", "vector_d", context__.to_vec(N));
        validate_non_negative_index("length", "N", N);
        length = vector_d(static_cast<Eigen::VectorXd::Index>(N));
        vals_r__ = context__.vals_r("length");
        pos__ = 0;
        size_t length_i_vec_lim__ = N;
        for (size_t i_vec__ = 0; i_vec__ < length_i_vec_lim__; ++i_vec__) {
            length[i_vec__] = vals_r__[pos__++];
        }
        validate_non_negative_index("age", "N", N);
        context__.validate_dims("data initialization", "age", "vector_d", context__.to_vec(N));
        validate_non_negative_index("age", "N", N);
        age = vector_d(static_cast<Eigen::VectorXd::Index>(N));
        vals_r__ = context__.vals_r("age");
        pos__ = 0;
        size_t age_i_vec_lim__ = N;
        for (size_t i_vec__ = 0; i_vec__ < age_i_vec_lim__; ++i_vec__) {
            age[i_vec__] = vals_r__[pos__++];
        }

        // validate, data variables
        check_greater_or_equal(function__,"N",N,1);
        // initialize data variables

        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed data

        // validate, set parameter ranges
        num_params_r__ = 0U;
        param_ranges_i__.clear();
        ++num_params_r__;
        ++num_params_r__;
        ++num_params_r__;
        ++num_params_r__;
    }

    ~model_vb() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("k")))
            throw std::runtime_error("variable k missing");
        vals_r__ = context__.vals_r("k");
        pos__ = 0U;
        context__.validate_dims("initialization", "k", "double", context__.to_vec());
        // generate_declaration k
        double k(0);
        k = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,k);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable k: ") + e.what());
        }

        if (!(context__.contains_r("linf")))
            throw std::runtime_error("variable linf missing");
        vals_r__ = context__.vals_r("linf");
        pos__ = 0U;
        context__.validate_dims("initialization", "linf", "double", context__.to_vec());
        // generate_declaration linf
        double linf(0);
        linf = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,linf);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable linf: ") + e.what());
        }

        if (!(context__.contains_r("sigma")))
            throw std::runtime_error("variable sigma missing");
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("initialization", "sigma", "double", context__.to_vec());
        // generate_declaration sigma
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sigma);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sigma: ") + e.what());
        }

        if (!(context__.contains_r("t0")))
            throw std::runtime_error("variable t0 missing");
        vals_r__ = context__.vals_r("t0");
        pos__ = 0U;
        context__.validate_dims("initialization", "t0", "double", context__.to_vec());
        // generate_declaration t0
        double t0(0);
        t0 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(t0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable t0: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        // model parameters
        stan::io::reader<T__> in__(params_r__,params_i__);

        T__ k;
        (void) k;  // dummy to suppress unused var warning
        if (jacobian__)
            k = in__.scalar_lb_constrain(0,lp__);
        else
            k = in__.scalar_lb_constrain(0);

        T__ linf;
        (void) linf;  // dummy to suppress unused var warning
        if (jacobian__)
            linf = in__.scalar_lb_constrain(0,lp__);
        else
            linf = in__.scalar_lb_constrain(0);

        T__ sigma;
        (void) sigma;  // dummy to suppress unused var warning
        if (jacobian__)
            sigma = in__.scalar_lb_constrain(0,lp__);
        else
            sigma = in__.scalar_lb_constrain(0);

        T__ t0;
        (void) t0;  // dummy to suppress unused var warning
        if (jacobian__)
            t0 = in__.scalar_constrain(lp__);
        else
            t0 = in__.scalar_constrain();


        // transformed parameters


        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters

        const char* function__ = "validate transformed params";
        (void) function__;  // dummy to suppress unused var warning

        // model body
        try {

            lp_accum__.add(normal_log<propto__>(k, 0, 5));
            lp_accum__.add(normal_log<propto__>(linf, 0, 300));
            lp_accum__.add(normal_log<propto__>(sigma, 0, 2));
            lp_accum__.add(normal_log<propto__>(t0, 0, 50));
            lp_accum__.add(lognormal_log<propto__>(length, log(multiply(linf,subtract(1,exp(multiply(-(k),subtract(age,t0)))))), sigma));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("k");
        names__.push_back("linf");
        names__.push_back("sigma");
        names__.push_back("t0");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "model_vb_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double k = in__.scalar_lb_constrain(0);
        double linf = in__.scalar_lb_constrain(0);
        double sigma = in__.scalar_lb_constrain(0);
        double t0 = in__.scalar_constrain();
        vars__.push_back(k);
        vars__.push_back(linf);
        vars__.push_back(sigma);
        vars__.push_back(t0);

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning



        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters

        // write transformed parameters

        if (!include_gqs__) return;
        // declare and define generated quantities


        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate generated quantities

        // write generated quantities
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_vb";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "k";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "linf";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "t0";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "k";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "linf";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "t0";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (!include_gqs__) return;
    }

}; // model

}




// Code generated by Stan version 2.16.0

#include <stan/model/model_header.hpp>

namespace model_vb_aging_error_gamma_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_vb_aging_error_gamma");
    reader.add_event(32, 32, "end", "model_vb_aging_error_gamma");
    return reader;
}

class model_vb_aging_error_gamma : public prob_grad {
private:
    int N;
    vector_d length;
    vector_d age;
    double cv_age;
public:
    model_vb_aging_error_gamma(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_vb_aging_error_gamma(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_vb_aging_error_gamma_namespace::model_vb_aging_error_gamma";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        context__.validate_dims("data initialization", "N", "int", context__.to_vec());
        N = int(0);
        vals_i__ = context__.vals_i("N");
        pos__ = 0;
        N = vals_i__[pos__++];
        validate_non_negative_index("length", "N", N);
        context__.validate_dims("data initialization", "length", "vector_d", context__.to_vec(N));
        validate_non_negative_index("length", "N", N);
        length = vector_d(static_cast<Eigen::VectorXd::Index>(N));
        vals_r__ = context__.vals_r("length");
        pos__ = 0;
        size_t length_i_vec_lim__ = N;
        for (size_t i_vec__ = 0; i_vec__ < length_i_vec_lim__; ++i_vec__) {
            length[i_vec__] = vals_r__[pos__++];
        }
        validate_non_negative_index("age", "N", N);
        context__.validate_dims("data initialization", "age", "vector_d", context__.to_vec(N));
        validate_non_negative_index("age", "N", N);
        age = vector_d(static_cast<Eigen::VectorXd::Index>(N));
        vals_r__ = context__.vals_r("age");
        pos__ = 0;
        size_t age_i_vec_lim__ = N;
        for (size_t i_vec__ = 0; i_vec__ < age_i_vec_lim__; ++i_vec__) {
            age[i_vec__] = vals_r__[pos__++];
        }
        context__.validate_dims("data initialization", "cv_age", "double", context__.to_vec());
        cv_age = double(0);
        vals_r__ = context__.vals_r("cv_age");
        pos__ = 0;
        cv_age = vals_r__[pos__++];

        // validate, data variables
        check_greater_or_equal(function__,"N",N,1);
        check_greater_or_equal(function__,"length",length,0);
        check_greater_or_equal(function__,"age",age,0);
        check_greater_or_equal(function__,"cv_age",cv_age,0);
        // initialize data variables

        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed data

        // validate, set parameter ranges
        num_params_r__ = 0U;
        param_ranges_i__.clear();
        ++num_params_r__;
        ++num_params_r__;
        ++num_params_r__;
        ++num_params_r__;
        validate_non_negative_index("age_true", "N", N);
        num_params_r__ += N;
    }

    ~model_vb_aging_error_gamma() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("k")))
            throw std::runtime_error("variable k missing");
        vals_r__ = context__.vals_r("k");
        pos__ = 0U;
        context__.validate_dims("initialization", "k", "double", context__.to_vec());
        // generate_declaration k
        double k(0);
        k = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,k);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable k: ") + e.what());
        }

        if (!(context__.contains_r("linf")))
            throw std::runtime_error("variable linf missing");
        vals_r__ = context__.vals_r("linf");
        pos__ = 0U;
        context__.validate_dims("initialization", "linf", "double", context__.to_vec());
        // generate_declaration linf
        double linf(0);
        linf = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,linf);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable linf: ") + e.what());
        }

        if (!(context__.contains_r("cv_length")))
            throw std::runtime_error("variable cv_length missing");
        vals_r__ = context__.vals_r("cv_length");
        pos__ = 0U;
        context__.validate_dims("initialization", "cv_length", "double", context__.to_vec());
        // generate_declaration cv_length
        double cv_length(0);
        cv_length = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,cv_length);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable cv_length: ") + e.what());
        }

        if (!(context__.contains_r("t0")))
            throw std::runtime_error("variable t0 missing");
        vals_r__ = context__.vals_r("t0");
        pos__ = 0U;
        context__.validate_dims("initialization", "t0", "double", context__.to_vec());
        // generate_declaration t0
        double t0(0);
        t0 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(t0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable t0: ") + e.what());
        }

        if (!(context__.contains_r("age_true")))
            throw std::runtime_error("variable age_true missing");
        vals_r__ = context__.vals_r("age_true");
        pos__ = 0U;
        validate_non_negative_index("age_true", "N", N);
        context__.validate_dims("initialization", "age_true", "vector_d", context__.to_vec(N));
        // generate_declaration age_true
        vector_d age_true(static_cast<Eigen::VectorXd::Index>(N));
        for (int j1__ = 0U; j1__ < N; ++j1__)
            age_true(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lb_unconstrain(0,age_true);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable age_true: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        // model parameters
        stan::io::reader<T__> in__(params_r__,params_i__);

        T__ k;
        (void) k;  // dummy to suppress unused var warning
        if (jacobian__)
            k = in__.scalar_lb_constrain(0,lp__);
        else
            k = in__.scalar_lb_constrain(0);

        T__ linf;
        (void) linf;  // dummy to suppress unused var warning
        if (jacobian__)
            linf = in__.scalar_lb_constrain(0,lp__);
        else
            linf = in__.scalar_lb_constrain(0);

        T__ cv_length;
        (void) cv_length;  // dummy to suppress unused var warning
        if (jacobian__)
            cv_length = in__.scalar_lb_constrain(0,lp__);
        else
            cv_length = in__.scalar_lb_constrain(0);

        T__ t0;
        (void) t0;  // dummy to suppress unused var warning
        if (jacobian__)
            t0 = in__.scalar_constrain(lp__);
        else
            t0 = in__.scalar_constrain();

        Eigen::Matrix<T__,Eigen::Dynamic,1>  age_true;
        (void) age_true;  // dummy to suppress unused var warning
        if (jacobian__)
            age_true = in__.vector_lb_constrain(0,N,lp__);
        else
            age_true = in__.vector_lb_constrain(0,N);


        // transformed parameters
        T__ alpha_age;
        (void) alpha_age;  // dummy to suppress unused var warning

        stan::math::initialize(alpha_age, DUMMY_VAR__);
        stan::math::fill(alpha_age,DUMMY_VAR__);
        T__ alpha_length;
        (void) alpha_length;  // dummy to suppress unused var warning

        stan::math::initialize(alpha_length, DUMMY_VAR__);
        stan::math::fill(alpha_length,DUMMY_VAR__);


        try {
            stan::math::assign(alpha_age, inv(pow(cv_age,2.0)));
            stan::math::assign(alpha_length, inv(pow(cv_length,2.0)));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters
        if (stan::math::is_uninitialized(alpha_age)) {
            std::stringstream msg__;
            msg__ << "Undefined transformed parameter: alpha_age";
            throw std::runtime_error(msg__.str());
        }
        if (stan::math::is_uninitialized(alpha_length)) {
            std::stringstream msg__;
            msg__ << "Undefined transformed parameter: alpha_length";
            throw std::runtime_error(msg__.str());
        }

        const char* function__ = "validate transformed params";
        (void) function__;  // dummy to suppress unused var warning
        check_greater_or_equal(function__,"alpha_age",alpha_age,0);
        check_greater_or_equal(function__,"alpha_length",alpha_length,0);

        // model body
        try {

            lp_accum__.add(normal_log<propto__>(k, 0, 5));
            lp_accum__.add(normal_log<propto__>(linf, 0, 300));
            lp_accum__.add(normal_log<propto__>(t0, 0, 50));
            lp_accum__.add(student_t_log<propto__>(cv_length, 3, 0, 2));
            lp_accum__.add(gamma_log<propto__>(age, alpha_age, elt_divide(alpha_age,age_true)));
            lp_accum__.add(gamma_log<propto__>(length, alpha_length, elt_divide(alpha_length,multiply(linf,subtract(1,exp(multiply(-(k),subtract(age_true,t0))))))));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("k");
        names__.push_back("linf");
        names__.push_back("cv_length");
        names__.push_back("t0");
        names__.push_back("age_true");
        names__.push_back("alpha_age");
        names__.push_back("alpha_length");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "model_vb_aging_error_gamma_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double k = in__.scalar_lb_constrain(0);
        double linf = in__.scalar_lb_constrain(0);
        double cv_length = in__.scalar_lb_constrain(0);
        double t0 = in__.scalar_constrain();
        vector_d age_true = in__.vector_lb_constrain(0,N);
        vars__.push_back(k);
        vars__.push_back(linf);
        vars__.push_back(cv_length);
        vars__.push_back(t0);
        for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(age_true[k_0__]);
        }

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        double alpha_age(0.0);
        (void) alpha_age;  // dummy to suppress unused var warning

        stan::math::initialize(alpha_age, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(alpha_age,DUMMY_VAR__);
        double alpha_length(0.0);
        (void) alpha_length;  // dummy to suppress unused var warning

        stan::math::initialize(alpha_length, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(alpha_length,DUMMY_VAR__);


        try {
            stan::math::assign(alpha_age, inv(pow(cv_age,2.0)));
            stan::math::assign(alpha_length, inv(pow(cv_length,2.0)));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters
        check_greater_or_equal(function__,"alpha_age",alpha_age,0);
        check_greater_or_equal(function__,"alpha_length",alpha_length,0);

        // write transformed parameters
        vars__.push_back(alpha_age);
        vars__.push_back(alpha_length);

        if (!include_gqs__) return;
        // declare and define generated quantities


        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate generated quantities

        // write generated quantities
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_vb_aging_error_gamma";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "k";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "linf";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "cv_length";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "t0";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "age_true" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_age";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_length";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "k";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "linf";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "cv_length";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "t0";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "age_true" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_age";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_length";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__) return;
    }

}; // model

}




// Code generated by Stan version 2.16.0

#include <stan/model/model_header.hpp>

namespace model_vb_gamma_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_vb_gamma");
    reader.add_event(32, 32, "end", "model_vb_gamma");
    return reader;
}

class model_vb_gamma : public prob_grad {
private:
    int N;
    vector_d length;
    vector_d age;
public:
    model_vb_gamma(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_vb_gamma(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_vb_gamma_namespace::model_vb_gamma";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        context__.validate_dims("data initialization", "N", "int", context__.to_vec());
        N = int(0);
        vals_i__ = context__.vals_i("N");
        pos__ = 0;
        N = vals_i__[pos__++];
        validate_non_negative_index("length", "N", N);
        context__.validate_dims("data initialization", "length", "vector_d", context__.to_vec(N));
        validate_non_negative_index("length", "N", N);
        length = vector_d(static_cast<Eigen::VectorXd::Index>(N));
        vals_r__ = context__.vals_r("length");
        pos__ = 0;
        size_t length_i_vec_lim__ = N;
        for (size_t i_vec__ = 0; i_vec__ < length_i_vec_lim__; ++i_vec__) {
            length[i_vec__] = vals_r__[pos__++];
        }
        validate_non_negative_index("age", "N", N);
        context__.validate_dims("data initialization", "age", "vector_d", context__.to_vec(N));
        validate_non_negative_index("age", "N", N);
        age = vector_d(static_cast<Eigen::VectorXd::Index>(N));
        vals_r__ = context__.vals_r("age");
        pos__ = 0;
        size_t age_i_vec_lim__ = N;
        for (size_t i_vec__ = 0; i_vec__ < age_i_vec_lim__; ++i_vec__) {
            age[i_vec__] = vals_r__[pos__++];
        }

        // validate, data variables
        check_greater_or_equal(function__,"N",N,1);
        // initialize data variables

        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed data

        // validate, set parameter ranges
        num_params_r__ = 0U;
        param_ranges_i__.clear();
        ++num_params_r__;
        ++num_params_r__;
        ++num_params_r__;
        ++num_params_r__;
    }

    ~model_vb_gamma() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("k")))
            throw std::runtime_error("variable k missing");
        vals_r__ = context__.vals_r("k");
        pos__ = 0U;
        context__.validate_dims("initialization", "k", "double", context__.to_vec());
        // generate_declaration k
        double k(0);
        k = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,k);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable k: ") + e.what());
        }

        if (!(context__.contains_r("linf")))
            throw std::runtime_error("variable linf missing");
        vals_r__ = context__.vals_r("linf");
        pos__ = 0U;
        context__.validate_dims("initialization", "linf", "double", context__.to_vec());
        // generate_declaration linf
        double linf(0);
        linf = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,linf);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable linf: ") + e.what());
        }

        if (!(context__.contains_r("cv_length")))
            throw std::runtime_error("variable cv_length missing");
        vals_r__ = context__.vals_r("cv_length");
        pos__ = 0U;
        context__.validate_dims("initialization", "cv_length", "double", context__.to_vec());
        // generate_declaration cv_length
        double cv_length(0);
        cv_length = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,cv_length);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable cv_length: ") + e.what());
        }

        if (!(context__.contains_r("t0")))
            throw std::runtime_error("variable t0 missing");
        vals_r__ = context__.vals_r("t0");
        pos__ = 0U;
        context__.validate_dims("initialization", "t0", "double", context__.to_vec());
        // generate_declaration t0
        double t0(0);
        t0 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(t0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable t0: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        // model parameters
        stan::io::reader<T__> in__(params_r__,params_i__);

        T__ k;
        (void) k;  // dummy to suppress unused var warning
        if (jacobian__)
            k = in__.scalar_lb_constrain(0,lp__);
        else
            k = in__.scalar_lb_constrain(0);

        T__ linf;
        (void) linf;  // dummy to suppress unused var warning
        if (jacobian__)
            linf = in__.scalar_lb_constrain(0,lp__);
        else
            linf = in__.scalar_lb_constrain(0);

        T__ cv_length;
        (void) cv_length;  // dummy to suppress unused var warning
        if (jacobian__)
            cv_length = in__.scalar_lb_constrain(0,lp__);
        else
            cv_length = in__.scalar_lb_constrain(0);

        T__ t0;
        (void) t0;  // dummy to suppress unused var warning
        if (jacobian__)
            t0 = in__.scalar_constrain(lp__);
        else
            t0 = in__.scalar_constrain();


        // transformed parameters
        T__ alpha_length;
        (void) alpha_length;  // dummy to suppress unused var warning

        stan::math::initialize(alpha_length, DUMMY_VAR__);
        stan::math::fill(alpha_length,DUMMY_VAR__);


        try {
            stan::math::assign(alpha_length, inv(pow(cv_length,2.0)));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters
        if (stan::math::is_uninitialized(alpha_length)) {
            std::stringstream msg__;
            msg__ << "Undefined transformed parameter: alpha_length";
            throw std::runtime_error(msg__.str());
        }

        const char* function__ = "validate transformed params";
        (void) function__;  // dummy to suppress unused var warning
        check_greater_or_equal(function__,"alpha_length",alpha_length,0);

        // model body
        try {

            lp_accum__.add(normal_log<propto__>(k, 0, 5));
            lp_accum__.add(normal_log<propto__>(linf, 0, 300));
            lp_accum__.add(normal_log<propto__>(t0, 0, 50));
            lp_accum__.add(student_t_log<propto__>(cv_length, 3, 0, 2));
            lp_accum__.add(gamma_log<propto__>(length, alpha_length, elt_divide(alpha_length,multiply(linf,subtract(1,exp(multiply(-(k),subtract(age,t0))))))));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("k");
        names__.push_back("linf");
        names__.push_back("cv_length");
        names__.push_back("t0");
        names__.push_back("alpha_length");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "model_vb_gamma_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double k = in__.scalar_lb_constrain(0);
        double linf = in__.scalar_lb_constrain(0);
        double cv_length = in__.scalar_lb_constrain(0);
        double t0 = in__.scalar_constrain();
        vars__.push_back(k);
        vars__.push_back(linf);
        vars__.push_back(cv_length);
        vars__.push_back(t0);

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        double alpha_length(0.0);
        (void) alpha_length;  // dummy to suppress unused var warning

        stan::math::initialize(alpha_length, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(alpha_length,DUMMY_VAR__);


        try {
            stan::math::assign(alpha_length, inv(pow(cv_length,2.0)));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters
        check_greater_or_equal(function__,"alpha_length",alpha_length,0);

        // write transformed parameters
        vars__.push_back(alpha_length);

        if (!include_gqs__) return;
        // declare and define generated quantities


        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate generated quantities

        // write generated quantities
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_vb_gamma";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "k";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "linf";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "cv_length";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "t0";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_length";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "k";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "linf";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "cv_length";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "t0";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_length";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__) return;
    }

}; // model

}




#endif
